### ISSUE TITLE
Optimize webpack configuration

### ISSUE THREAD

**Issue by ascariandrea** [buildo/webpack-docker-dev-tools#19]
## requirements
- make webpack load `less` files
- make webpack load vendor assets from `src/app/assets` folder with `url-loader`
- make webpack load `sass-variables` files
- make webpack export `config` as global variable

## specs
- add specific loaders `less-loader`, `sass-variables-loader` and `url-loader`
- add `CONFIG: JSON.stringify(config)` to `webpack.DefinePlugin`

**Comment by giogonzo** [comment]
not relevant anymore
